# Pytorch Assignment 1

### 5 Interesting Functions

PyTorch is developed by Facebook AI Research lab, chose the following functions:
- bernoulli
- tril
- cartesian_prod
- where
- linspace

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.bernoulli

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

In [2]:
# Example 1 - working 
a = torch.empty(3, 3).uniform_(0, 1)
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

Sample 3X3 matrix with values between 0 and 1.

In [3]:
# Example 2 - working
# a = torch.zeros(3,3)
a = torch.ones(2,2)
torch.bernoulli(a)

tensor([[1., 1.],
        [1., 1.]])

Sample 2X2 matrix with all 1's.

In [4]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.empty(2)
torch.bernoulli(a)

RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

Input values between 0 and 1 are accepted, others values result in error.

Bernoulli is a probability distribution. Torch.bernoulli() returns a binary value (i.e. either 0 or 1).

## Function 2 - torch.tril

Returns the lower triangular part of the matrix (2-D tensor) or batch of matrices

In [5]:
# Example 1 - working
b = torch.randn(4, 6)
print(b)
torch.tril(b, diagonal=0)

tensor([[ 0.3145, -1.4407, -1.0762,  1.7703,  0.2617, -1.0929],
        [ 0.6704,  0.2785, -1.1693, -0.2539, -0.1268,  0.7463],
        [ 1.8891,  0.7779, -0.1084, -1.5226, -0.3980,  1.0751],
        [ 0.7488, -1.0843,  0.7285, -0.4216, -2.0041, -0.0289]])


tensor([[ 0.3145,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6704,  0.2785,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.8891,  0.7779, -0.1084,  0.0000,  0.0000,  0.0000],
        [ 0.7488, -1.0843,  0.7285, -0.4216,  0.0000,  0.0000]])

Lower triangular part is controlled by diagonal attribute value

In [6]:
# Example 2 - working
b = torch.randn(4, 6)
print(b)
torch.tril(b, diagonal=-1)

tensor([[ 1.5975, -2.4727,  0.1801,  1.1275, -2.5285, -2.8889],
        [-0.8369,  0.7267, -0.3296,  0.2250,  1.6410, -0.2842],
        [-0.5182,  2.0969,  0.1797, -1.1841, -0.6064,  0.6548],
        [-1.7241, -0.0057, -0.9235,  1.4514,  0.4035,  1.1869]])


tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.8369,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.5182,  2.0969,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.7241, -0.0057, -0.9235,  0.0000,  0.0000,  0.0000]])

Lower triangular size is decreased by negative diagonal value and increased by positive diagonal value

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
b = []
print(b)
torch.tril(b, diagonal=-1, out=None)

[]


TypeError: tril(): argument 'input' (position 1) must be Tensor, not list

Tried to break it other ways, not successful. Input with list is an option.

## Function 3 - torch.cartesian_prod

Do cartesian product of the given sequence of tensors. The behavior is similar to python's `itertools.product`.

In [8]:
# Example 1 - working
a = [2, 3]
b = [4, 5, 6]
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[2, 4],
        [2, 5],
        [2, 6],
        [3, 4],
        [3, 5],
        [3, 6]])

Cartesian Product of a and b

In [9]:
# Example 2 - working
a = [1, 3, 4]
b = [4, 5, 6]
c = [7, 8, 9]
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
tensor_c = torch.tensor(c)
torch.cartesian_prod(tensor_a, tensor_b, tensor_c)

tensor([[1, 4, 7],
        [1, 4, 8],
        [1, 4, 9],
        [1, 5, 7],
        [1, 5, 8],
        [1, 5, 9],
        [1, 6, 7],
        [1, 6, 8],
        [1, 6, 9],
        [3, 4, 7],
        [3, 4, 8],
        [3, 4, 9],
        [3, 5, 7],
        [3, 5, 8],
        [3, 5, 9],
        [3, 6, 7],
        [3, 6, 8],
        [3, 6, 9],
        [4, 4, 7],
        [4, 4, 8],
        [4, 4, 9],
        [4, 5, 7],
        [4, 5, 8],
        [4, 5, 9],
        [4, 6, 7],
        [4, 6, 8],
        [4, 6, 9]])

Cartesian Product of a, b and c. 

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
a = [1, 3, 4]
b = [4, 5, 6.]
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

RuntimeError: meshgrid expects all tensors to have the same dtype

Error is self explanatory. All tensors to be of same data types for cartesian_prod function.

## Function 4 - torch.where

Return a tensor of elements selected from either input or other depending on condition. 

In [11]:
# Example 1 - working
x = torch.randn(3, 3)
y = torch.ones(3, 3)
print(x)
torch.where(x > 0, x, y)

tensor([[ 0.7642, -0.4203, -0.7752],
        [ 0.9830,  0.7902, -1.3048],
        [-0.1822,  0.1687,  0.4865]])


tensor([[0.7642, 1.0000, 1.0000],
        [0.9830, 0.7902, 1.0000],
        [1.0000, 0.1687, 0.4865]])

Tensor replaces x values with y values based on the condition.

In [12]:
# Example 2 - working
x = torch.zeros(2, 3)
y = torch.ones(2, 3)
print(x)
torch.where(x > 0, x, y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

Complete Replacement of x with y

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(3, 3)
y = torch.ones(3, 2)
print(x)
torch.where(x > 0, x, y)

tensor([[-0.1908,  1.5695, -0.1528],
        [ 0.9033, -1.3942,  1.2217],
        [ 0.8911, -0.7608,  1.8331]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Both input and other tensor should be of same size.

## Function 5 - torch.linspace

Returns a one-dimensional tensor of equal steps

In [14]:
# Example 1 - working
torch.linspace(3, 15, steps=5)

tensor([ 3.,  6.,  9., 12., 15.])

Uniform sized steps from start to end 

In [15]:
# Example 2 - working
torch.linspace(start=-10, end=10, steps=1)

tensor([-10.])

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(start=-10, end=10, steps=-1)

RuntimeError: number of steps must be non-negative

Error is self explanatory. 

## Conclusion

A newbee's exploration of Pytorch functions - bernoulli, tril, cartesian_prod, where and linspace

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
